typography_spectrum: 0.5358423
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
layout_spectrum: 0.9713262
title: ABI-INC
purpose: []
color:
  saturation: 0.3340103814844042
  brandStrength: 0.4856631
  rhythmicContrast: 0.75
  brandColors:
    - '#381809'
    - '#d0a875'
    - '#6b5a52'
    - '#fafefe'
    - '#c12800'
  lightness: 0.3796634562313557
cta:
  bucket: null
  version: null
  domain: null
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
name: American Building Interiors
