typography_spectrum: 0.90948
color:
  brandColors:
    - '#381809'
    - '#d0a875'
    - '#6b5a52'
    - '#fafefe'
    - '#c12800'
  brandStrength: 0.6311382602434605
  lightness: 0.37966345623135567
  saturation: 0.3340103814844042
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: American Building Interiors
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ABI-INC
purpose: []
